### ISSUE TITLE
Player Metrics: Load time vs play time

### ISSUE THREAD

**Issue by pglowacky** [livepeer/ui-kit#209]
## Load time vs play time

This metric is used to measure any buffering or stalling by the player after the first frame for VOD assets. For example, if a user has played an asset for 10 seconds but for 8 seconds the video was buffering, we'd give that a score of 80%. 

### Must capture:
- Seconds that a viewer has watched a video after the first frame
- Seconds while a viewer is watching the video after the first frame where the video is not playing (e.g. buffering or stalling) 

@ecmulli Can you fill in details about how this data should be captured so that we can query it?

**Comment by ecmulli** [comment]
here is the formula we will use: `Play Time / (Play time + Load time) * 100`

your example isn't accurate, that would be a score of 20%. If a user played an asset for 30 seconds and spent 5 seconds loading (so 35 total elapsed seconds) their score would be 30 / 35 = 86%. 

Play Time: number of seconds video is playing in the player
Load Time: number of seconds video is not loading, e.g. buffering or stalling
Total Elapsed Time: Play Time + Load Time

We need to capture at least two of these (since we can infer the third). I'll let it up to the dev on the best way to do this. j

Also, i'm assuming this is most appropriate to write out once at the of the session, not continuously.
